import RealRooted.FactorialCompression.Definitions
import RealRooted.FactorialCompression.Boundary
import RealRooted.FactorialCompression.KernelIdentities
import RealRooted.FactorialCompression.Compression
import RealRooted.FactorialCompression.KernelGeometry
import RealRooted.FactorialCompression.DegreeChanging
import RealRooted.FactorialCompression.Lifting
import RealRooted.FactorialCompression.Theorems
